# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_disability', models.CharField(choices=[('청각 장애 있음', '청각 장애 있음'), ('청각 장애 없음', '청각 장애 없음')], max_length=20)),
                ('job', models.CharField(choices=[('중등 미만', '중등 미만'), ('중학생', '중학생'), ('고등학생', '고등학생'), ('대학생', '대학생'), ('기타', '기타')], default='기타', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
