# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('phone_num', models.CharField(blank=True, max_length=50)),
                ('lec', models.CharField(blank=True, max_length=100)),
                ('lec_url', models.CharField(blank=True, max_length=100)),
                ('lec_teacher', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('lec_company', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('view_cnt', models.IntegerField(blank=True, default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
