# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('모집중', '모집중'), ('준비중', '준비중'), ('제작중', '제작중'), ('배포완료', '배포완료'), ('제작중단', '제작중단')], default='모집중', max_length=20),
        ),
    ]
