# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
    ]
