# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('모집중', '_모집중'), ('준비중', '_준비중'), ('제작중', '_제작중'), ('제작중', '_배포완료'), ('제작중단', '_제작중단')], max_length=20),
        ),
    ]
