# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180319_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_username', models.CharField(blank=True, max_length=50)),
                ('j_phone_num', models.CharField(blank=True, max_length=50)),
                ('j_email', models.EmailField(max_length=254)),
                ('j_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('j_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Request')),
            ],
        ),
    ]
