# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpdesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('h_title', models.CharField(blank=True, max_length=100)),
                ('h_description', models.TextField()),
                ('h_lock_checked', models.CharField(choices=[('잠금', '잠금'), ('전체공개', '전체공개')], default='전체공개', max_length=20)),
                ('h_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
